### PR TITLE
ci: Fix pipeline tests

### LINKED ISSUE #34: Fix the CI
Due to the slower environment, the CI fails on some tests.

The issue appears to be that some tests complete before others, breaking the goldens

### PR DESCRIPTION
**Pull request by spydon**
Closes #34

### CODE REVIEW

File: packages/spec_cli/test/spec_cli_test.dart [hunk 1]
```diff
@@ -978,30 +989,71 @@ void main() {
...
+            lastFrame,
+            endsWith(
+              '''
+$failingTest
+$groupFailingTest
+$testResults
+''',
+            ),
+          );
+        }
```
Comment (spydon) [inline packages/spec_cli/test/spec_cli_test.dart:1056]: Is it possible to write this in a nicer way? Is it possible to do some "either or"-matcher or something?

Comment (trejdych) [reply packages/spec_cli/test/spec_cli_test.dart:1056]: https://api.flutter.dev/flutter/package-matcher_matcher/anyOf.html ?

Comment (spydon) [reply packages/spec_cli/test/spec_cli_test.dart:1056]: I searched so much for this yesterday because I knew it existed, thanks!

File: packages/spec_cli/test/spec_cli_test.dart [hunk 2]
```diff
@@ -171,16 +171,17 @@ void main() {
           options: SpecOptions.fromArgs(const ['.', '../b/test', '--no-ci']),
         );
 
+        final lastFrame = testRenderer.frames.last;
+        expect(lastFrame, contains('PASS  ../b/test/another_test.dart'));
+        expect(lastFrame, contains('PASS  test/my_test.dart'));
```
Comment (rrousselGit) [inline packages/spec_cli/test/spec_cli_test.dart:176]: I'm not super fond of this approach
It doesn't test the absence of anything extra

For example the output could be:

```dart
 PASS  ../b/test/another_test.dart
 PASS  test/my_test.dart
 PASS  test/my_test.dart
 PASS  test/my_test.dart
 PASS  test/my_test.dart

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Time:        00:00:00
```

which isn't good

Comment (spydon) [reply packages/spec_cli/test/spec_cli_test.dart:176]: If we do something permutations of `anyOf` then, where we include all the strings?

Comment (spydon) [reply packages/spec_cli/test/spec_cli_test.dart:176]: Or maybe even simpler, that we verify that the number of lines in the output also is correct?

Comment (spydon) [reply packages/spec_cli/test/spec_cli_test.dart]: Alright, go ahead! But maybe keep this PR as a backup then, so that the pipeline isn't broken for yet another year? :sweat_smile:

**Comment by rrousselGit** [comment]
Hum my solution didn't work. LEt's merge this then

**Comment by rrousselGit** [comment]
Thanks for your work!

**Comment by spydon** [comment]
> Thanks for your work!

Thanks! Could you maybe put the `hacktoberfest-accepted` tag on it too (trying to get some Hacktoberfest PRs outside of our own organization in)? 😄

> Hum my solution didn't work. LEt's merge this then

I updated one of the tests to check the number or lines and the number or empty lines, to make sure nothing unsuspected could be printed, should I do this for the rest of the tests too? I think only the tests that I updated in this PR are affected.

**Comment by rrousselGit** [comment]
The repo is tagged with hacktoberfest already. Labelling the pr shouldn't be needed

**Comment by rrousselGit** [comment]
> I updated one of the tests to check the number or lines and the number or empty lines, to make sure nothing unsuspected could be printed, should I do this for the rest of the tests too? I think only the tests that I updated in this PR are affected.

 I still don't really like this solution
What I would like is to have a way to force the test order. 

The tricky part is having a solution that works between different `main`

**Comment by spydon** [comment]
>  I still don't really like this solution
> What I would like is to have a way to force the test order. 
> 
> The tricky part is having a solution that works between different `main` 

If we force a test result order, it doesn't feel like the test is actually properly testing the real output?

**Comment by rrousselGit** [comment]
Fair enough, let me mark the PR

**Comment by rrousselGit** [comment]
> If we force a test result order, it doesn't feel like the test is actually properly testing the real output?

It is. It's just that the output isn't random anymore, it's deterministic

**Comment by spydon** [comment]
> It is. It's just that the output isn't random anymore, it's deterministic

Isn't that part of what these tests are testing? That even though there are races in the output, the final output will be properly formatted. Because it should not be modified to run deterministically when it is running a user's test suite right, only in the CI?

**Comment by rrousselGit** [comment]
No. That's like if I were to test the rendering of a clock. I don't want my test to run using the CI's time. I want to mock the time to test a very specific scenario.

**Comment by spydon** [comment]
> No. That's like if I were to test the rendering of a clock. I don't want my test to run using the CI's time. I want to mock the time to test a very specific scenario.

That makes sense, thanks for clarifying!
